### ISSUE TITLE
Consider implementations for the update request

### ISSUE THREAD

**Issue by kwannoel** [Holmusk/HolmuskDB#32]
1) We wait until the user presses save, then we batch all the modifications and send it to the backend. (Current interface)

    Under the hood this requires us to cache the updates on the client side, until the user decides to lock it in and save it

2) We update it as the user adds in changes. (+1 Noel)

    This approach avoids having to store the updates since we can immediately send update requests to the backend server.

**Comment by dzhou343** [comment]
Currently writing working on implementing the queries for option 2

Current issue I have ran into: 

Because of the way we have setup the request structure in the Pipeline Interface notion page, the query will always be sent in entirety even when we only need a subset of the information.

For example, if we would like to add a label to a resource/term, we only need the current labels of that resource, the value of the term, and the new label. However, in our current request implementation, we would send unnecessary info such as the name of a person and their relationships to the term. 

In addition, because in the current request structure there is no way to easily differentiate what a "new label" is, as currently implemented we would have to delete all existing labels and then recreate them. 

I propose the following request structure (for now, just to update labels): 

```
{ "type" : "addLabel"
 , "term" : 80008000
 , "labels" : ["handphone", "contact", "number"]
 , "newLabel" : "mobile number"
}
```

**Comment by kwannoel** [comment]
To pinpoint the `term`:

During term creation use UUID:
https://github.com/Holmusk/HolmuskDB/issues/35

This allows us to query for the term's UUID and update it

**Comment by kwannoel** [comment]
Let's rely on neo4j's native ids for nodes until #35 is implemented.

**Comment by kwannoel** [comment]
Closed by above commit
